from setuptools import setup, find_packages

setup(name='webinars_web',
    version='1.0',
    description='Webinars Django Project',
    author='Michael Prior',
    zip_safe=False,
    include_package_data=True,
    author_email='mprior@hubspot.com',
    url=' http://hubspot.com/',
    install_requires=[
        'hsdjango>=2.2,<2.2hubspot',
        'Django==1.3',
        'PyYAML==3.10',
        'pymssql==1.0.2',
        'requests==0.10.7',
        'dse-hubspot',
        'sanetime>=4.0,<5.0',
        'gtwpy>=1.3.6,<1.4',
        'webexpy>=2.2.6,<3.0',
        'cynq>=2.3.11,<2.4',
        'hapipy>=2.8,<2.9',
        'hspy>=1.6.0,<1.7',
        'grabbag>=0.11,<0.12',
        'giftwrap>=1.5.5,<1.6',
        'hapicake>=0.1.0,<0.2',
        'django-debug-toolbar==0.9.4',
        'hapi_plus>=2.0.9,<2.0.9hubspot',
        'hapicrank>=1.1,<1.1hubspot',
        'style_guide>=1.1,<1.1hubspot',
        'hsforms>=1.0,<1.0hubspot',
        'segments>=1.0,<1.0hubspot',
        'sfdc_info>=1.0,<1.0hubspot',
        'raven>=1.7.3',
    ],
    dependency_links=[
        "https://bitbucket.org/weholt/dse2/get/545e114008b8.tar.bz2#egg=dse-hubspot",
    ],
    packages=find_packages(),
)

